version: '3.9'
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 8005:8000
#    depends_on:
#      - database
#
#  database:
#    image: mysql:5.7.22
#    restart: always
#    environment:
#      MYSQL_DATABASE: dev_database
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - .dbdata:/var/lib/mysql
#    ports:
#      - 33068:3306

