# This dockerfile is kicked off from the docker-compose command, it starts the server after ensure the mysql service is already running.
FROM python:3.9

# Prevents python from writing pyc files to disc
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . /app

RUN ["chmod", "+x", "/app/docker-entrypoint.sh"]

ENTRYPOINT ["/app/docker-entrypoint.sh"]

CMD python manage.py runserver 0.0.0.0:8000
